name: build

on: [ push, pull_request ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.0
      - uses: actions/setup-dotnet@v3.0.3
        with:
          dotnet-version: 6.x
      - uses: cake-build/cake-action@v1.4.1
      - uses: actions/checkout@v3.1.2
        with:
          name: PowerHost.dll
          path: bin/Release/net6.0/PowerHost.dll